### ISSUE TITLE
Confusing Code

### ISSUE THREAD

**Issue by rwedoff** [Microsoft/PowerBI-visuals-docs#1]
The code for creating SelectionIds is confusing.  There are variables that aren't declared/explained, such as i, j, and cats.
![code](https://cloud.githubusercontent.com/assets/6679636/16317334/3826aec2-3950-11e6-8666-105e7fa1d7e0.PNG)

**Comment by wesyao** [comment]
We've fixed the undefined variable and will be updating the documentation soon.

![image](https://cloud.githubusercontent.com/assets/16310155/17002662/362d3e10-4e81-11e6-9c8e-95a05f2a5399.png)

Essentially, your category and measure are defined within your capability. Category is your grouping in the dataRoles section and Measure is your measure.
