### ISSUE TITLE
Error when starting a new visual of template "table"

### ISSUE THREAD

**Issue by chuijh** [Microsoft/PowerBI-visuals-docs#17]
Hi, I created a new visual from template table. I got an error when trying to start it(see below). Do you know how to fix it?

PS C:\Users\Joe\yoheiVisual\yoheiVisual> pbiviz start
 info   Building visual...
 error  TYPESCRIPT   File 'C:/Users/Joe/yoheiVisual/yoheiVisual/typings/index.d.ts' not found.
 error  TYPESCRIPT  /src/visual.ts : (7,25) Cannot find namespace 'd3'.
 error  TYPESCRIPT  /src/visual.ts : (8,24) Cannot find namespace 'd3'.
 error  TYPESCRIPT  /src/visual.ts : (9,24) Cannot find namespace 'd3'.
 error  TYPESCRIPT  /src/visual.ts : (10,24) Cannot find namespace 'd3'.
 error  TYPESCRIPT  /src/visual.ts : (13,40) Cannot find name 'd3'.
 error  TYPESCRIPT  /src/visual.ts : (28,36) Cannot find name 'd3'.
 error  TYPESCRIPT  /src/visual.ts : (63,26) Cannot find name 'd3'.
 error  TYPESCRIPT  /src/visual.ts : (64,20) Cannot find name 'd3'.

**Comment by chuijh** [comment]
Figured out I need to install the d3 library

**Comment by wesyao** [comment]
For more context, you have to add your index.d.ts to the tsconfig.json.
