### ISSUE TITLE
No docs on adding external libraries

### ISSUE THREAD

**Issue by scottsen** [Microsoft/PowerBI-visuals-docs#18]
Just a stub now, but... I'm stuck with         private hostContainer: JQuery;
   /src/visual.ts : (4,32) Cannot find name 'JQuery'.
which used to work... and now I can't figure out how to add JQuery support.

**Comment by scottsen** [comment]
btw, clicking the "Send Feedback" button merely took me to this document site, so I am kinda assuming they are pushing me towards adding Issues like this?

**Comment by spatney** [comment]
![image](https://cloud.githubusercontent.com/assets/12804419/17261759/655a5738-558c-11e6-83ab-d06e6aeffd19.png)

**Comment by spatney** [comment]
i just did typings install dt~jquery -G and it worked.

**Comment by spatney** [comment]
also, we will be adding detailed docs on this today.

**Comment by wesyao** [comment]
Hey @scottsen, yep the feedback thing is expected. We want our issues reported through github.

**Comment by scottsen** [comment]
I'm good now.  

Two things happened:
1) I had put the wrong file in my  tsconfig.json 
2) I dunno.  I think my powershell instance was holding onto some bad modules/state.  Relaunching made things WAY better... :(

**Comment by spatney** [comment]
Awesome!
