### ISSUE TITLE
Documentation gap - does not specify how to view custom visual after compiling

### ISSUE THREAD

**Issue by ChamaraIC** [Microsoft/PowerBI-visuals-docs#19]
in https://github.com/Microsoft/PowerBI-visuals-docs/blob/master/tools/usage.md
"Viewing your visual in PowerBI" section just jumps to a screenshot that just shows the visual (no context). It should state how to view the visual on the browser. 

It took me some time to figure this out.

**Comment by wesyao** [comment]
Thanks for the feedback! I'll update this section to provide you with more context from when you start to server to adding the debug visual.

**Comment by wesyao** [comment]
The update has been added. Check it out!

**Comment by ChamaraIC** [comment]
Cool!
