### ISSUE TITLE
Selection Manager Not Working

### ISSUE THREAD

**Issue by rwedoff** [Microsoft/PowerBI-visuals-docs#4]
When trying to select a bar in my code (I followed the instructions via the docs here), no matter which bar I select, the last bar is highlighted and not the correct bar. 

![image](https://cloud.githubusercontent.com/assets/6679636/16931934/1eeb56f2-4d09-11e6-8662-423da5dfb7f7.png)

**Comment by wesyao** [comment]
Selection manager just tells the host which item was selected. Highlighting inside your visual is part of the visual's logic.

**Comment by rwedoff** [comment]
Which ever bar I select on my chart, the last bar on your (the other chart) is selected. I can select "Junior" and that last bar will still be the that highlights on the bottom default chart.

**Comment by spatney** [comment]
Could you share the code snip that generates the selection id? if possible also the JSON for your dataview.

**Comment by rwedoff** [comment]
private setVisualDataValueArray(values: string[], count: number[], splitValues: string[]): VisualDataValue[] {
            /*Walks through the dataView*/
            let dataValueArray: VisualDataValue[] = [];
            let isSplitValues = true;
            if(splitValues == null){
                isSplitValues = false;
            }
            values.forEach((item: string, index: number) => {
                let categoricalData: DataViewCategorical = this.dataView.categorical;
                let category:DataViewCategoricalColumn = categoricalData.categories[0];
                let categories: DataViewValueColumns = categoricalData.values; 
                let itemData = category.values[index];
                let selector: ISelectionId = this.selectionIdBuilder
                    .withSeries(categories, itemData)
                    .withCategory(this.dataView.categorical.categories[0], index)
                    .createSelectionId(); 
                if(isSplitValues){
                    dataValueArray.push({
                        count: count[index],
                        value: values[index],
                        splitValue: splitValues[index],
                        selectionId: selector
                    });
                } else{
                    dataValueArray.push({
                        count: count[index],
                        value: values[index],
                        selectionId: selector
                    });
                }                
            });
            return dataValueArray;
        }




JSON:


{
  "metadata": {
    "columns": {
      "0": {
        "roles": {
          "axis": true
        },
        "type": {
          "underlyingType": 1,
          "category": null
        },
        "displayName": "If you are a University of Iowa student, what year are you?",
        "queryName": "Movie Data.If you are a University of Iowa student, what year are you?",
        "expr": {
          "_kind": 1,
          "source": {
            "_kind": 0,
            "entity": "Movie Data",
            "variable": "m"
          },
          "ref": "If you are a University of Iowa student, what year are you?"
        }
      },
      "1": {
        "roles": {
          "clusteredValue": true
        },
        "type": {
          "underlyingType": 260,
          "category": null
        },
        "displayName": "Count of If you are a University of Iowa student, what year are you?",
        "queryName": "CountNonNull(Movie Data.If you are a University of Iowa student, what year are you?)",
        "expr": {
          "_kind": 3,
          "arg": {
            "_kind": 1,
            "source": {
              "_kind": 0,
              "entity": "Movie Data",
              "variable": "m"
            },
            "ref": "If you are a University of Iowa student, what year are you?"
          },
          "func": 5
        }
      },
      "2": {
        "roles": {
          "clusteredSeries": true
        },
        "type": {
          "underlyingType": 1,
          "category": null
        },
        "displayName": "How likely is it that you would be drinking if you were not to have attended this event?",
        "queryName": "Movie Data.How likely is it that you would be drinking if you were not to have attended this event?",
        "expr": {
          "_kind": 1,
          "source": {
            "_kind": 0,
            "entity": "Movie Data",
            "variable": "m"
          },
          "ref": "How likely is it that you would be drinking if you were not to have attended this event?"
        }
      }
    }
  },
  "categorical": {
    "categories": {
      "0": {
        "source": {
          "roles": {
            "axis": true
          },
          "type": {
            "underlyingType": 1,
            "category": null
          },
          "displayName": "If you are a University of Iowa student, what year are you?",
          "queryName": "Movie Data.If you are a University of Iowa student, what year are you?",
          "expr": {
            "_kind": 1,
            "source": {
              "_kind": 0,
              "entity": "Movie Data",
              "variable": "m"
            },
            "ref": "If you are a University of Iowa student, what year are you?"
          }
        }
      },
      "1": {
        "source": {
          "roles": {
            "clusteredSeries": true
          },
          "type": {
            "underlyingType": 1,
            "category": null
          },
          "displayName": "How likely is it that you would be drinking if you were not to have attended this event?",
          "queryName": "Movie Data.How likely is it that you would be drinking if you were not to have attended this event?",
          "expr": {
            "_kind": 1,
            "source": {
              "_kind": 0,
              "entity": "Movie Data",
              "variable": "m"
            },
            "ref": "How likely is it that you would be drinking if you were not to have attended this event?"
          }
        }
      }
    },
    "values": {
      "0": {
        "source": {
          "roles": {
            "clusteredValue": true
          },
          "type": {
            "underlyingType": 260,
            "category": null
          },
          "displayName": "Count of If you are a University of Iowa student, what year are you?",
          "queryName": "CountNonNull(Movie Data.If you are a University of Iowa student, what year are you?)",
          "expr": {
            "_kind": 3,
            "arg": {
              "_kind": 1,
              "source": {
                "_kind": 0,
                "entity": "Movie Data",
                "variable": "m"
              },
              "ref": "If you are a University of Iowa student, what year are you?"
            },
            "func": 5
          }
        }
      }
    }
  }
}

**Comment by wesyao** [comment]
Thanks for reporting this! We're currently investigating this issue.

**Comment by spatney** [comment]
meanwhile, can you try doing this -> (<any>powerbi.visuals).SelectionIdBuilder.builder() to create the builder vs the host?

**Comment by spatney** [comment]
ok I know what is the problem. Our docs are wrong :) You need to re-create the builder per id we generate. The problem here is you are using the same builder. Sorry about this, we'll update the docs.

**Comment by wesyao** [comment]
Updated the docs. Notice I create the selectionbuilder inside the loop now.

![image](https://cloud.githubusercontent.com/assets/16310155/17122490/b36572e0-5290-11e6-834a-4d1ec5ea325d.png)
