### ISSUE TITLE
Limit on data size?

### ISSUE THREAD

**Issue by Drjoachim** [Microsoft/PowerBI-visuals-docs#44]
Hi, 

I was wondering if there is a limit on size of the data you get into your custom visual.
The following code always returns "1000" even if there are more rows provided in the dataset.

```
module powerbi.extensibility.visual {
    function visualTransform(options: VisualUpdateOptions, host: IVisualHost): string {
        return options.dataViews[0].table.rows.length.toString();
    }
    export class Visual implements IVisual {
        private target: HTMLElement;
        private rowCount: string;
        private host: IVisualHost;

        constructor(options: VisualConstructorOptions) {
            console.log('Visual constructor', options);
            this.target = options.element;
            this.rowCount = "0";
        }

        public update(options: VisualUpdateOptions) {
            console.log('Visual update', options);
            this.rowCount = visualTransform(options, this.host);
            
            this.target.innerHTML = `<p><em>${(this.rowCount)}</em></p>`;
        }

        public destroy(): void {
            //TODO: Perform any cleanup tasks here
        }
    }
}
```
When filtering (with another visual) the rows below 1000 then the count is correct. 

How can I load all the rows in the custom visual?

Kr,
Joachim

**Comment by spatney** [comment]
All you need is to specify a count for the data reduction of your role. The max is 30000.

An example is like this
```
    "dataViewMappings": [
        {
            "table": {
                "rows": {
                    "dataReductionAlgorithm": {
                      "top": {
                          "count": 30000
                      }  
                    },
                    "for": {
                        "in": "values"
                    }
                }
            }
        }
    ],
```

**Comment by spatney** [comment]
Note count is an approximation, and not exact. so it may return a few more rows.

**Comment by ragnargylfa** [comment]
Hello, 
Where do you enter the below information to extend the dataset?

 "dataViewMappings": [
        {
            "table": {
                "rows": {
                    "dataReductionAlgorithm": {
                      "top": {
                          "count": 30000
                      }  
                    },
                    "for": {
                        "in": "values"
                    }
                }
            }
        }
    ],

**Comment by xiangzprime8** [comment]
capabilities.json
